name: Azure Arc Connect (Self-Hosted)

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Name of the Kubernetes cluster'
        required: true
        default: 'AzureArcVClusterTestPOC'
      resourceGroup:
        description: 'Azure Resource Group name'
        required: true
        default: 'AzureArcVClusterTest'
      location:
        description: 'Azure region (e.g. WestUS3)'
        required: true
        default: 'WestUS3'

jobs:
  connect-arc:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Resource Group
      run: |
        az group create \
          --name "${{ github.event.inputs.resourceGroup }}" \
          --location "${{ github.event.inputs.location }}" \
          --output table

    - name: Connect Cluster to Azure Arc
      run: |
        az connectedk8s connect \
          --name "${{ github.event.inputs.clusterName }}" \
          --resource-group "${{ github.event.inputs.resourceGroup }}"
